"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import type { PitchRun, RunStatus } from "../lib/runs/types";
import styles from "./studio.module.css";

const stages: Array<{ key: RunStatus; label: string }> = [
  { key: "understanding", label: "UNDERSTAND" }, { key: "verifying", label: "VERIFY" }, { key: "planning", label: "PLAN" }, { key: "producing", label: "PRODUCE" }, { key: "reviewing", label: "REVIEW" }, { key: "delivered", label: "DELIVER" }
];
const rank: Record<RunStatus, number> = { idle: -1, collecting: 0, understanding: 0, verifying: 1, planning: 2, producing: 3, reviewing: 4, delivered: 5, failed: -1 };

export default function StudioWorkspace({ runId }: { runId: string }) {
  const [run, setRun] = useState<PitchRun>(); const [error, setError] = useState(""); const analysisStarted = useRef(false); const productionStarted = useRef(false);
  const load = useCallback(async () => { if (!runId) return; const response = await fetch(`/api/runs/${runId}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Run not found."); setRun(payload.run); }, [runId]);
  const invoke = useCallback(async (action: "analyze" | "produce") => { setError(""); const response = await fetch(`/api/runs/${runId}/${action}`, { method: "POST" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || `${action} failed.`); setRun(payload.run); }, [runId]);
  useEffect(() => { load().catch(cause => setError(cause instanceof Error ? cause.message : String(cause))); }, [load]);
  useEffect(() => { if (run?.status === "collecting" && !analysisStarted.current) { analysisStarted.current = true; invoke("analyze").catch(cause => { setError(cause instanceof Error ? cause.message : String(cause)); load().catch(() => undefined); }); } }, [run, invoke, load]);
  useEffect(() => { if (!run || !["understanding", "verifying", "producing", "reviewing"].includes(run.status)) return; const interval = window.setInterval(() => load().catch(() => undefined), 1200); return () => window.clearInterval(interval); }, [run, load]);
  async function produce() { if (productionStarted.current) return; productionStarted.current = true; setRun(current => current ? { ...current, status: "producing" } : current); try { await invoke("produce"); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); await load().catch(() => undefined); } finally { productionStarted.current = false; } }
  if (!runId) return <Empty title="No run selected" message="Submit a public GitHub repository from the landing page to begin."/>;
  if (!run && !error) return <Empty title="Opening production control room" message="Loading the persisted run…"/>;
  if (!run) return <Empty title="Run unavailable" message={error}/>;
  const result = run.intelligenceResult; const intel = result?.intelligence; const lock = result?.claimLock; const manifest = result?.storyManifest;
  const counts = lock?.claims.reduce((acc, claim) => ({ ...acc, [claim.status]: acc[claim.status] + 1 }), { SUPPORTED: 0, PARTIAL: 0, UNSUPPORTED: 0 }) ?? { SUPPORTED: 0, PARTIAL: 0, UNSUPPORTED: 0 };
  return <main className={styles.shell}>
    <header className={styles.header}><Link href="/" className={styles.brand}><span className={styles.mark}/><span>EchoPitch</span></Link><div className={styles.runMeta}><span className={styles.liveDot}/><span>{run.status}</span><code>{run.id.slice(0,8)}</code></div></header>
    <section className={styles.pipeline} aria-label="Production pipeline">{stages.map((stage,index) => <div key={stage.key} className={`${styles.stage} ${rank[run.status] >= index ? styles.complete : ""} ${run.status === stage.key ? styles.active : ""}`}><span>{String(index+1).padStart(2,"0")}</span>{stage.label}</div>)}</section>
    <div className={styles.layout}><aside className={styles.sidebar}><p className={styles.eyebrow}>RUN CONFIGURATION</p><a href={run.input.githubUrl} target="_blank" rel="noreferrer">{run.input.githubUrl.replace("https://github.com/", "")}</a><dl><dt>Audience</dt><dd>{run.input.audience}</dd><dt>Goal</dt><dd>{run.input.pitchGoal}</dd><dt>Duration</dt><dd>{run.input.targetDuration}s</dd></dl>{run.status === "planning" && <button className={styles.produceButton} onClick={produce}>Produce and assemble pitch</button>}<p className={styles.note}>DELIVER completes only after a playable final artifact is assembled and persisted.</p></aside>
    <div className={styles.content}>{(run.error || error) && <section className={`${styles.panel} ${styles.failure}`}><p className={styles.eyebrow}>FAILED</p><h2>Run stopped honestly</h2><p>{run.error || error}</p></section>}
      <section className={styles.panel}><PanelHead number="01" title="Understand" status={intel ? "COMPLETE" : run.status.toUpperCase()}/>{intel ? <><h2>{intel.productName}</h2><p className={styles.summary}>{intel.summary}</p><div className={styles.grid3}><Metric label="Capabilities" value={intel.capabilities.length}/><Metric label="Mechanisms" value={intel.technicalMechanisms.length}/><Metric label="Paths inspected" value={intel.inspectedPaths.length}/></div><h3>Implemented capabilities</h3><div className={styles.tags}>{intel.capabilities.length ? intel.capabilities.map(item => <span key={item.id}>{item.name}</span>) : <em>Insufficient evidence.</em>}</div><h3>Technical mechanisms</h3>{intel.technicalMechanisms.length ? <ul>{intel.technicalMechanisms.map(item => <li key={item.id}>{item.name} — {item.description}</li>)}</ul> : <em>Insufficient evidence.</em>}<details><summary>Inspected repository paths ({intel.inspectedPaths.length})</summary>{intel.inspectedPaths.map(path => <p key={path}><code>{path}</code></p>)}</details>{intel.limitations.length > 0 && <details><summary>Evidence limitations ({intel.limitations.length})</summary>{intel.limitations.map(item => <p key={item}>{item}</p>)}</details>}</> : <Working text="Collecting and inspecting prioritized repository files…"/>}</section>
      <section className={styles.panel}><PanelHead number="02" title="Verify" status={lock ? "COMPLETE" : "WAITING"}/>{lock ? <><p className={styles.eyebrow}>{lock.claims.length} CANDIDATE CLAIMS</p><div className={styles.grid3}><Metric label="Supported" value={counts.SUPPORTED}/><Metric label="Partial / rewritten" value={counts.PARTIAL}/><Metric label="Rejected" value={counts.UNSUPPORTED}/></div><div className={styles.claims}>{lock.claims.map(claim => <details key={claim.id} className={styles.claim}><summary><span className={styles[claim.status.toLowerCase()]}>{claim.status}</span>{claim.claim}</summary><p>{claim.reason}</p>{claim.allowedNarration && claim.allowedNarration !== claim.claim && <p>Allowed narration: {claim.allowedNarration}</p>}{claim.evidence.map(ev => <a key={ev.id} href={ev.url} target="_blank" rel="noreferrer">{ev.path} — {ev.reason}</a>)}{claim.status !== "SUPPORTED" && <strong>Excluded from narration</strong>}</details>)}</div></> : <Working text="ClaimLock waits for repository evidence."/>}</section>
      <section className={styles.panel}><PanelHead number="03" title="Plan" status={manifest ? "COMPLETE" : "WAITING"}/>{manifest ? <><div className={styles.scenes}>{manifest.scenes.map(scene => <article key={scene.sceneId} className={styles.scene}><header><span>{scene.sceneId}</span><b>{scene.duration}s</b></header><h3>{scene.purpose}</h3><p>{scene.narration}</p><small>{scene.visualIntent}</small><footer><span>{scene.recommendedMediaType}</span><code>{scene.claimIds.join(", ") || "no verified claim"}</code></footer></article>)}</div>{run.mediaPlan && <><h3>Media Plan</h3><div className={styles.receipt}>{run.mediaPlan.map(item => <article key={item.sceneId}><b>{item.sceneId} → {item.preferredVisualSource}</b><p>{item.productionRationale}</p><code>{item.livepeerCapability || item.repositoryAsset || "Rendered evidence card"}</code></article>)}</div></>}</> : <Working text="Story Director waits for verified claims."/>}</section>
      <section className={styles.panel}><PanelHead number="04" title="Produce" status={run.instructions ? (run.status === "delivered" ? "COMPLETE" : run.status.toUpperCase()) : "READY AFTER PLAN"}/>{run.instructions ? <div className={styles.productionList}>{run.instructions.map(instruction => { const production=run.productions?.find(item=>item.sceneId===instruction.sceneId); const latest=production?.attempts.at(-1)?.result; return <article key={instruction.sceneId}><header><b>{instruction.sceneId}</b><span>{instruction.mediaSource === "livepeer-generated" ? "LIVEPEER GENERATED" : "REPOSITORY EVIDENCE"}</span></header><p>{production ? production.finalVerdict : "Waiting / executing"}</p>{instruction.requestedCapability && <dl><dt>Requested</dt><dd>{instruction.requestedCapability}</dd><dt>Executed</dt><dd>{latest?.executedCapability || "Not returned yet"}</dd><dt>Attempt</dt><dd>{latest ? production?.attempts.length : 0}</dd><dt>Job</dt><dd>{latest ? (latest.jobId || "Not provided") : "Pending"}</dd></dl>}{latest?.error && <pre>{latest.error}</pre>}</article>})}</div> : <Working text="Production has not been started. No artifact is marked generated."/>}</section>
      <section className={styles.panel}><PanelHead number="05" title="Review" status={run.productions ? (run.status === "delivered" ? "COMPLETE" : run.status.toUpperCase()) : "WAITING"}/>{run.productions ? run.productions.map(item => <article className={styles.review} key={item.sceneId}><b>{item.sceneId}</b><strong>{item.finalVerdict}</strong>{item.attempts.map(attempt => <div key={attempt.attempt}><span>Attempt {attempt.attempt}: {attempt.critic.verdict}</span>{attempt.critic.problems.map(problem => <p key={problem}>{problem}</p>)}{attempt.repairPlan && <p>REPAIR → {attempt.repairPlan.revisedInstruction.prompt}</p>}</div>)}{item.warning && <p>WARNING — {item.warning}</p>}</article>) : <Working text="Critic results appear only after real production attempts."/>}</section>
      <section className={styles.panel}><PanelHead number="06" title="Deliver" status={run.finalAssembly?.status === "completed" ? "COMPLETE" : "WAITING"}/>{run.productionReceipt && run.finalAssembly && result ? <><iframe className={styles.finalPitch} src={run.finalAssembly.artifactReference} title="Final assembled EchoPitch" allow="autoplay"/><div className={styles.deliveryActions}><a href={run.finalAssembly.artifactReference} target="_blank" rel="noreferrer">Open final pitch</a><a href={run.finalAssembly.downloadReference}>Download HTML artifact</a></div><div className={styles.grid3}><Metric label="Duration (seconds)" value={run.finalAssembly.duration}/><Metric label="Scenes" value={run.finalAssembly.sceneCount}/><Metric label="Livepeer assets" value={run.productionReceipt.livepeerGeneratedAssetCount}/></div><p className={styles.note}>Narration: {run.finalAssembly.narrationAudioStatus}. Format: {run.finalAssembly.format}.</p><h3>Evidence Receipt</h3><div className={styles.receipt}>{result.storyManifest.scenes.map(scene => <article key={scene.sceneId}><b>{scene.narration}</b>{scene.evidenceReferences.map(ref => <div key={ref.claimId}><code>→ {ref.claimId}</code>{ref.evidenceIds.map(id => { const ev=intel?.evidence.find(e=>e.id===id); return <a key={id} href={ev?.url} target="_blank" rel="noreferrer">→ {ev?.path || id}</a>})}</div>)}</article>)}</div><h3>Production Receipt</h3><div className={styles.receipt}>{run.productionReceipt.scenes.map(scene => <article key={scene.sceneId}><b>{scene.sceneId} → {scene.mediaSource}</b><code>{scene.executedCapability || "No Livepeer capability required"} · {scene.attempts} attempt(s) · {scene.finalVerdict}</code>{scene.finalOutputReference && <a href={scene.finalOutputReference} target="_blank" rel="noreferrer">→ scene artifact</a>}</article>)}<article><b>Final assembly → {run.productionReceipt.assembly.status}</b><code>{run.productionReceipt.assembly.sceneOrder.join(" → ")}</code><code>{run.productionReceipt.totalLivepeerGenerations} Livepeer generation(s) · {run.productionReceipt.repairAttempts} repair(s)</code></article></div></> : <Working text="Delivery waits for successful final assembly. A failed assembly is never marked delivered."/>}</section>
    </div></div>
  </main>;
}
function Empty({title,message}:{title:string;message:string}) { return <main className={styles.empty}><span className={styles.mark}/><h1>{title}</h1><p>{message}</p><Link href="/">Return to EchoPitch</Link></main>; }
function PanelHead({number,title,status}:{number:string;title:string;status:string}) { return <header className={styles.panelHead}><div><span>{number}</span><h2>{title}</h2></div><code>{status}</code></header>; }
function Metric({label,value}:{label:string;value:number}) { return <div className={styles.metric}><b>{value}</b><span>{label}</span></div>; }
function Working({text}:{text:string}) { return <p className={styles.working}>{text}</p>; }
